### ISSUE TITLE
Wrong getItemViewType position argument

### ISSUE THREAD

**Issue by aimtechnology** [chthai64/overscroll-bouncy-android#3]
In this method you pass "position - 1" because your lib handle first and last item for bouncing.

```
@Override
    public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
        if (position != 0 && position != getItemCount() - 1) {
            mAdapter.onBindViewHolder(holder, position - 1);
        }
    }
```

But here position passed directly. This leads to unexpected behaviour because original mAdapter.getItemViewType NEVER called with zero position - your lib always intercept this call. Only position>0 proceed to real adapter. In my case I use custom row for first item (with position == 0) and it never populated.

```
    @Override
    public int getItemViewType(int position) {
        if (position == 0)
            return VIEW_TYPE_HEADER;

        if (position == getItemCount() - 1)
            return VIEW_TYPE_FOOTER;

        return mAdapter.getItemViewType(position);
    }
```

Now I am temporary using this in my code:

```
        @Override
        public int getItemViewType(int position)
        {
            position = position-1;
            return position == 0?1:2; // zero row is 1 type, other is 2
        }
```

After this fix all works as expected.

But real fix is looks like: return mAdapter.getItemViewType(position**_-1_**);
in method public int getItemViewType(int position) in BouncyAdapter class.

**Comment by chthai64** [comment]
Thank you so much for your fix. I will put that into the code.
